### ISSUE TITLE
疑问请教

### ISSUE THREAD

**Issue by reenWYJ** [neoremind/coddding#1]
在您的文章中:http://neoremind.com/2018/12/2018-polar-race-java-no-1/   我有个小问题:

"load vlog采用direct io",可以直接缓存到heap里面吗? 就不用再用unsafe.copymemory()了

**Comment by neoremind** [comment]
第三阶段vlog是每个分片加载到堆外内存的，使用direct io方式，所以不在heap。访问这个堆外内存方式可以用Unsafe提供的copyMemory方法。

**Comment by reenWYJ** [comment]
> 第三阶段vlog是每个分片加载到堆外内存的，使用direct io方式，所以不在heap。访问这个堆外内存方式可以用Unsafe提供的copyMemory方法。

谢谢回复,不过我的疑问是通过unsafe.copymemory(),相当于做了一次内存转移(offheap转移到heap)
为什么不直接缓存到heap中呢?

**Comment by reenWYJ** [comment]
通过阅读您的代码,学到很多,谢谢
